version: '3.8'

services:
  backend:
    build: .
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - MONGODB_URI=mongodb://mongodb:27017/finance_dashboard
      - JWT_SECRET=8h3aS@Lq9$W^x2KPz7@GkD5bE0tM1eC
      - JWT_EXPIRE=24h
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
